class DependencyBuilder(object):
    def __init__(self):
        """
        Builds a dependency.
        """
        pass

    def setup(self, source_dir: str, header_dir: str, lib_dir: str, exec_dir: str):
        """
        Builds a dependency and installs artifacts into the specified directories.

        :param source_dir: A path to a directory containing the source code for a dependency.
        :param header_dir: A path to the output directory for public headers from this dependency.
        :param lib_dir: A path to the output directory for libraries generated by this dependency.
        :param exec_dir: A path to the output directory for executables generated by this dependency.
        """
        raise NotImplementedError()
